version: 0.0.1
logging_level: 'DEBUG'
device_uuid: '2222'
ble:
  device_name: 'Herbarium'
  services:
    device_identity:
      uuid: '180a' # Device information
  characteristics:
    device_identity:
        uuid: '2a25' # Serial number string
        descriptors:
          - uuid: '2901'
            value: 'Get the device uuid'