version: 0.0.1
logging_level: 'DEBUG'
device_uuid: '2222'
ble:
  device_name: 'Herbarium'
  services:
    device_identity:
      uuid: '180a' # Device information
  characteristics:
    device_identity:
        uuid: '2a25' # Serial number string
        descriptors:
          - uuid: '2901'
            value: 'Get the device uuid'
status_indicator:
  led_count: 16
  gpio_data_in: 18 # According to the documentation, should be one of GPIO10, GPIO12, GPIO18 or GPIO21. Ref: https://learn.adafruit.com/neopixels-on-raspberry-pi/raspberry-pi-wiring
  # Minimum time allowed by pattern when there is multiple pattern at the same time. This time is in seconds.
  multi_animation_maximum_time: 10
  # Number of milliseconds between each update
  interval_update: 10