version: 0.8.0

time_zone_offfset: -5

logging:
  level: 'DEBUG'
  path: 'logs'
  filename_suffix: '.log'
device_uuid: '47804a3a-20d6-b1f3-1e1b-95d8e47d7ae0'
ble:
  device_name: 'Herbarium'
  services:
    device_information:
      uuid: '180a' # Device information
    setup_device:
      uuid: 'f08a607d-bb1f-4fd3-adb1-2c3d580c6d0c'
  characteristics:
    device_identity:
      uuid: '2a25' # Serial number string
      descriptors:
        - uuid: '2901'
          value: 'Get the device uuid'
    connection_status:
      uuid: '47f46eb3-0777-48ba-9c2b-66303b21a167'
      descriptors:
    setup_wifi:
      uuid: 'ddb4c99c-d127-4314-bb6f-597c4cb1859d'
      descriptors:
plant_count: 16
hygrometry:
  delta_detection: 8 # % delta use for deteting the adding or the  removig of a plant
  interval_update: 500 # ms
  max_sample_before_regulation: 120 # use or execute the regulation after a define number of sample (120*interval_update = 60sec)
  shot_duration: 3000 # ms
  pump_speed: 75 # %

luminosity:
  interval_update: 50 # ms
  time_range_center: 14 #h

status_indicator:
  led_count: 16
  gpio_data_in: 18 # Pin 12, According to the documentation, should be one of GPIO10, GPIO12, GPIO18 or GPIO21. Ref: https://learn.adafruit.com/neopixels-on-raspberry-pi/raspberry-pi-wiring
  # Minimum time allowed by pattern when there is multiple pattern at the same time. This time is in seconds.
  multi_animation_maximum_time: 5
  # Number of milliseconds between each update
  interval_update: 10
led_strip:
  gpio_data_in: 21 # Pin 40
  led_count: 320 # Total Lightning LED number in the whole herbarium
  led_by_tile: 20 # Number of LED by tile
valve:
  gpio_selector_pin_S0: 5 # Pin 29
  gpio_selector_pin_S1: 6 # Pin 31
  gpio_selector_pin_S2: 19 # Pin 35
  gpio_selector_pin_S3: 26 # Pin 37
  gpio_position_out: 12 # Pin 32
  pwm_freq: 50
  position_off: 8
  position_on: 3
  opening_time: 200 # ms
  closing_time: 500 # ms
pump:
  gpio_speed_out: 13 # Pin 33
  pwm_freq: 50
  max_speed: 100
  min_speed: 50
api:
  api_key: ''
  base_url: 'https://botand-herbarium-api.herokuapp.com/api'
data_synchronization_task:
  # Interval and delays are in seconds
  send_logs:
    interval: 600 # update every 10 min
    delay: 350 # wait 5 min before the first call
  update_data:
    interval: 350 # update every 5min
    delay: 0
  check_new_plant:
    interval: 30 # check every minutes
    delay: 90 # wait 1 min before the first call
  check_removed_plant:
    interval: 30 # check every minutes
    delay: 150 # wait 2 min before first call
adc_config:
  i2c_sda: 2
  i2c_scl: 3
  adc_channel_ambient_luminosity: 0
  adc_channel_water_level: 1
  adc_channel_plant_hygrometry: 2
  gpio_selector_pin_S0: 8 # Pin 24
  gpio_selector_pin_S1: 7 # Pin 26
  gpio_selector_pin_S2: 16 # Pin 36
  gpio_selector_pin_S3: 20 # Pin 38
