"""BLE Characteristic module"""
from .device_identity_characteristic import DeviceIdentityCharacteristic
from .connection_status_characteristic import ConnectionStatusCharacteristic
from .setup_wifi_characteristic import SetupWifiCharacteristic
