"""LEDs utils"""
from src.models import StatusPattern

# Colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_GREEN = (0, 255, 0)
COLOR_VIOLET = (64, 53, 111)
COLOR_LEAF_GREEN = (136, 189, 94)
COLOR_ORANGE = (173, 114, 24)

# Type of animation
BREATHING_ANIMATION = 0
SPINNING_ANIMATION = 1
SOLID_ANIMATION = 2
BLINKING_ANIMATION = 3
THEATRE_CHASE_ANIMATION = 4

# Defined patterns
INTERNET_CONNECTION_UNHEALTHY_PATTERN = StatusPattern(
    'internet_connection_unhealthy',
    COLOR_ORANGE,
    BREATHING_ANIMATION)
